name: Build LibrePods Linux

on: 
  push:
#    branches:
#      - '*'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: use DavidAnson/markdownlint-action
        uses: DavidAnson/markdownlint-cli2-action@v21
        continue-on-error: true
        with: 
          globs: '**/*.md'
      
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build \
            qt6-base-dev qt6-declarative-dev qt6-svg-dev \
            qt6-tools-dev qt6-tools-dev-tools qt6-connectivity-dev \
            libxkbcommon-dev

      - name: Build project
        working-directory: linux
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja
          ninja

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: librepods-linux
          path: linux/build/librepods

  debian-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: make script executable
        run: chmod +x ./linux.sh
      - name: Start Bash script
        id: bash-script
        run: bash ./linux.sh
        continue-on-error: false
      - name: error handling
        if: ${{steps.bash-script.outcome == '1' }}
        run: echo "Bash script failed"
      
      
      
